name: Terraform Plan and Apply with Chekov

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        type: choice
        options:
          - dev
          - stage
          - prod

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Chekov Security Checks
      run: |
        checkov -d .

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.10.3

    - name: Terraform Init
      run: terraform init -backend-config="key=terraform/state/${{ github.event.inputs.environment }}"

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan -var-file=${{ github.event.inputs.environment }}.tfvars

    - name: Terraform Apply
      if: ${{ github.event.inputs.environment == 'prod' || github.event.inputs.environment == 'stage' || github.event.inputs.environment == 'dev' }}
      run: terraform apply -auto-approve -var-file=${{ github.event.inputs.environment }}.tfvars

    - name: Output Public IPs
      run: terraform output public_ips
      env:
        TF_LOG: INFO
