name: Terraform Destroy Workflow

on:
  workflow_dispatch:  # Allows manual trigger of the destroy workflow
    inputs:
      environment:
        type: choice
        description: Envornment
        options: 
        - dev
        - stage
        - prod
        - all
        default: test

jobs:
  destroy:
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Terraform Format
        run: terraform fmt -check

      # Step 3: Configure Azure Credentials (if using Azure)
      - name: Terraform plan 
        run: |
          cd 27
          az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          terraform init
          terraform workspace select ${{ github.event.inputs.environment }}
          terraform plan --destroy -var-file vars.${{ github.event.inputs.environment }}.tfvars -out ${{ github.event.inputs.environment }}.plan
      - name: Terraform apply
        run: |
          cd 27
              terraform workspace select ${{ github.event.inputs.environment }}
              terraform apply --auto-approve "${{ github.event.inputs.environment }}.plan"
